
spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.64.3
    port: 5672
    username: admin
    password: admin
  cloud:
    config:
      override-none: true
    
    
server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh