spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.64.128
    port: 5672
    username: admin
    password: admin
  cloud:
    config:
      override-none: true
     
server:
  port: 3001·
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#转发规则
#zuul:
 # routes:
  #  item-service: /item-service/**
   # user-service: /user-service/**
    #order-service: /order-service/**
zuul:
  retryable: true
  
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRestriesNextServcer: 1
  MaxAutoRetires: 1
  
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh